apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.0.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://:29092,PLAINTEXT_INTERNAL://kafka:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"



{{/*          ports:*/}}
{{/*              - containerPort: 9092*/}}
{{/*              - containerPort: 9093*/}}
{{/*              - containerPort: 9097*/}}
{{/*          env:*/}}

{{/*            - name: KAFKA_BROKER_ID*/}}
{{/*              value: "1"*/}}
{{/*            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP*/}}
{{/*              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"*/}}
{{/*            - name: KAFKA_ZOOKEEPER_CONNECT*/}}
{{/*              value: zookeeper:2181*/}}
{{/*            - name: KAFKA_LISTENERS*/}}
{{/*              value: INSIDE://kafka:9092,OUTSIDE://0.0.0.0:9093*/}}
{{/*            - name: KAFKA_ADVERTISED_LISTENERS*/}}
{{/*              value: "INSIDE://kafka:9092,OUTSIDE://localhost:9093"*/}}
{{/*            - name: KAFKA_INTER_BROKER_LISTENER_NAME*/}}
{{/*              value: INSIDE*/}}
{{/*            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR*/}}
{{/*              value: "1"*/}}
{{/*            - name: KAFKA_JMX_PORT*/}}
{{/*              value: "9997"*/}}
{{/*            - name: KAFKA_JMX_HOSTNAME*/}}
{{/*              value: kafka*/}}