apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  type: ClusterIP
  ports:
{{/*    - name: inside*/}}
      port: 9092
      targetPort: 9092
      protocol: TCP
{{/*    - name: outside*/}}
{{/*      port: 9093*/}}
{{/*      targetPort: 9093*/}}
{{/*      protocol: TCP*/}}
{{/*    - name: inside*/}}
{{/*      port: 9092*/}}
{{/*      targetPort: 9092*/}}
{{/*      protocol: TCP*/}}
{{/*    - name: outside*/}}
{{/*      port: 9093*/}}
{{/*      targetPort: 9093*/}}
{{/*      protocol: TCP*/}}
{{/*    - port: 9997*/}}
{{/*      name: jmx*/}}
{{/*      targetPort: 9997*/}}
{{/*      protocol: TCP*/}}
  selector:
    app: kafka