apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: postgres-db
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-persistent-storage
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-db-pvc