apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-db-pv
  labels:
    app: postgres-db
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data