{
 "title": "Spring Boot Cache (3.x)",
 "description": "This dashboard provides real-time monitoring of cache performance and status in a Spring Boot application. It uses Spring Boot Actuator to expose metrics, Prometheus for data collection, and Grafana for visualization.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(cache_gets_total,application)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(cache_gets_total{application=\"$application\"},cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cache_gets_total{application=~\"$application\", cluster=~\"$cluster\"},instance)"
    }
   },
   {
    "name": "cache_name",
    "label": "cache_name",
    "query": {
     "query": "label_values(cache_gets_total{application=\"$application\", cluster=~\"$cluster\", instance=~\"$instance\"}, cache)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Hit Rate (5m)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(cache_gets_total{application=\"$application\", cache=\"$cache_name\", cluster=~\"$cluster\", instance=~\"$instance\", result=\"hit\"}[5m]))\n  /\n  (\n    sum(rate(cache_gets_total{application=\"$application\", cache=\"$cache_name\", cluster=~\"$cluster\", instance=~\"$instance\", result=\"hit\"}[5m]))\n    +\n    sum(rate(cache_gets_total{application=\"$application\", cache=\"$cache_name\", cluster=~\"$cluster\", instance=~\"$instance\", result=\"miss\"}[5m]))\n  )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "cache_size{application=\"$application\", cache=\"$cache_name\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Count (1m)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "delta(cache_gets_total{application=\"$application\", cache=\"$cache_name\", cluster=~\"$cluster\", instance=~\"$instance\", result=\"hit\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Miss Count (1m)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "delta(cache_gets_total{application=\"$application\", cache=\"$cache_name\", cluster=~\"$cluster\", instance=~\"$instance\", result=\"miss\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}